cniClusterRole: msm-cni

cniConfigMap: msm-cni-config

webhookClusterRole: msm-admission-webhook-role

webhookClusterRoleBinding: msm-admission-webhook-binding

webhookServiceAccount: msm-admission-webhook-sa

gatewayDaemonSet: msm-gateway

gatewayName: gateway

webhookDeployment: msm-admission-webhook

controllerName: msm-controller

controllerDeployment: controller

cniImage:
  name: ciscolabs/msm-cni
  tag: latest

proxyImage:
  name: ciscolabs/msm-proxy
  tag: latest

stubImage:
  name: ciscolabs/msm-rtsp-stub
  tag: latest

webhookImage:
  name: ciscolabs/msm-admission-webhook
  tag: latest

controllerImage:
  name: ciscolabs/msm-controller
  tag: latest

clientImage:
  name: ciscolabs/rtsp-client
  tag: latest

serverImage:
  name: ciscolabs/rtsp-server
  tag: latest
